apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: icr-copy
spec:
  params:
  - name: ibmcloud-username
    description: Username of the IBM Cloud account
    default: ""
  - name: ibmcloud-password
    description: Password of the IBM Cloud account
    default: ""
  - name: region
    description: The region of where the registry is located
    default: ""
  - name: registry
    description: The registry of where the image resides
    default: ""
  - name: namespace
    description: The test namespace of where the image resides
    default: ""
  - name: namespace-staging
    description: The staging namespace of where the image resides
    default: ""
  - name: repository
    description: The repository of where the image resides
    default: ""
  steps:
    - name: ibmcloud-icr-copy
      # env:
      #   - name: ibmcloud-password
      #     valueFrom:
      #       secretKeyRef:
      #         name: secret-object
      #         key: secret_key
      image: ibmcom/pipeline-base-image
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "hello world"
          echo "$(params.ibmcloud-username)"
          echo "$(params.ibmcloud-password)"
          ibmcloud login -u "$(params.ibmcloud-username)" -p $(params.ibmcloud-password) -r "$(params.region)"
          ibmcloud cr image-tag "$(params.registry)"/"$(params.namespace)"/"$(params.repository)" "$(params.registry)"/"$(params.namespace-staging)"/"$(params.repository)"