apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skopeo-task
spec:
  workspaces:
    - name: images-url
  params:
    # - name: srcImageURL
    #   description: URL of the image to be copied to the destination registry
    #   type: string
    #   default: ""
    #   value: docker://$(params.image-url)/$(params.registry)/$(params.namespace)/$(params.image-name)
    # - name: destImageURL
    #   description: URL of the image where the image from source should be copied to
    #   type: string
    #   default: ""
    #   value: docker://$(params.registry-url)/$(params.registry-namespace-staging)/$(params.image-name-stg)
    - name: srcImageURL
      description: URL of the image to be copied to the destination registry
      type: string
      default: "dir:tekton/results/image-repository/us.icr.io/scct-test/scct-admin"
    - name: destImageURL
      description: URL of the image where the image from source should be copied to
      type: string
      default: "docker://us.icr.io/scct-stage/scct-admin:latest"
  steps:
    - name: skopeo-copy
      image: quay.io/vinamra2807/skopeo:latest
      script: |
        # Function to copy multiple images.
        #
        copyimages() {
          filename='$(workspaces.images-url.path)/url.txt'
          while IFS= read line || [ -n "$line" ]
          do 
            cmd=""
            for url in $line
            do
              # echo $url 
              cmd="$cmd \
                  $url"
            done
            skopeo copy $cmd
            echo $cmd
          done < "$filename"
        }
        #
        # If single image is to be copied then, it can be passed through
        # params in the taskrun.
        if [ "$(params.srcImageURL)" != "" ] && [ "$(params.destImageURL)" != "" ] ; then
          skopeo copy "$(params.srcImageURL)" "$(params.destImageURL)"
        else
          # If file is provided as a configmap in the workspace then multiple images can be copied.
          #
          copyimages
        fi



# apiVersion: tekton.dev/v1beta1
# kind: Task
# metadata:
#   name: skopeo-task
# spec:
#   workspaces:
#     - name: images-url
#   params:
#     # - name: srcImageURL
#     #   description: URL of the image to be copied to the destination registry
#     #   type: string
#     #   default: ""
#     #   value: docker://$(params.image-url)/$(params.registry)/$(params.namespace)/$(params.image-name)
#     # - name: destImageURL
#     #   description: URL of the image where the image from source should be copied to
#     #   type: string
#     #   default: ""
#     #   value: docker://$(params.registry-url)/$(params.registry-namespace-staging)/$(params.image-name-stg)
#     - name: srcImageURL
#       description: URL of the image to be copied to the destination registry
#       type: string
#       default: "dir:tekton/results/image-repository/us.icr.io/scct-test/scct-admin"
#     - name: destImageURL
#       description: URL of the image where the image from source should be copied to
#       type: string
#       default: "docker://us.icr.io/scct-stage/scct-admin:latest"
#   steps:
#     - name: skopeo-copy
#       image: quay.io/vinamra2807/skopeo:latest
#       script: |
#         check what the image looks like when its saved in the results area******